services:
  pm-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pm-app
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./backend/data:/app/backend/data
    restart: unless-stopped
